name = "notioncf1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "notioncf-db"
database_id = "a57c3449-0157-4e30-bfdc-40a8645681fa"

# KV Namespace
[[kv_namespaces]]
binding = "CACHE"
id = "9295d7728a28443dbc8346c581d33536"

[[kv_namespaces]]
binding = "DRAWINGS"
id = "1157474260fd42ce8484acc04d942323"

# R2 Bucket for file uploads
[[r2_buckets]]
binding = "FILES"
bucket_name = "notioncf-files"
